<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
<!--    <parent>-->
<!--        <groupId>cn.itbeien</groupId>-->
<!--        <artifactId>itbeien-mt</artifactId>-->
<!--        <version>${revision}</version>-->
<!--        <relativePath>../itbeien-mt/pom.xml</relativePath>-->
<!--    </parent>-->
    <groupId>cn.itbeien</groupId>
    <artifactId>dtpay</artifactId>
    <version>${revision}</version>
    <name>${project.artifactId}</name>
    <modules>
        <module>dtpay-merchant</module>
        <module>dtpay-payment</module>
        <module>dtpay-admin</module>
        <module>dtpay-common</module>
        <module>dtpay-task</module>
    </modules>
    <packaging>pom</packaging>
    <url>https://www.itbeien.cn</url>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <revision>1.0.0</revision>
        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
        <flatten-maven-plugin.version>1.6.0</flatten-maven-plugin.version>
    </properties>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.itbeien</groupId>
                <artifactId>itbeien-mt-system</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.itbeien</groupId>
                <artifactId>dtpay-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.itbeien</groupId>
                <artifactId>itbeien-mt-common</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>${project.name}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <!-- 统一 revision 版本 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    <updatePomFile>true</updatePomFile>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <target>${maven.compiler.target}</target>
                    <source>${maven.compiler.source}</source>
                    <encoding>UTF-8</encoding>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>