# \u6570\u636E\u6E90\u914D\u7F6E
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/dtpay2.0
spring.datasource.username=root
spring.datasource.password=${DB_PWD}

# MyBatis\u914D\u7F6E
# \u641C\u7D22\u6307\u5B9A\u5305\u522B\u540D
mybatis.typeAliasesPackage=cn.itbeien.**.entity
# \u914D\u7F6Emapper\u7684\u626B\u63CF\uFF0C\u627E\u5230\u6240\u6709\u7684mapper.xml\u6620\u5C04\u6587\u4EF6
mybatis.mapperLocations=classpath*:mapper/**/*Mapper.xml
# \u52A0\u8F7D\u5168\u5C40\u7684\u914D\u7F6E\u6587\u4EF6
#mybatis.configLocation=classpath:mybatis/mybatis-config.xml

# \u6587\u4EF6\u4E0A\u4F20 \u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
spring.servlet.multipart.max-file-size=10MB
# \u8BBE\u7F6E\u603B\u4E0A\u4F20\u7684\u6587\u4EF6\u5927\u5C0F
spring.servlet.multipart.max-request-size=20MB

project.config.copyright-year=2025
project.config.name=\u5B9A\u65F6\u4EFB\u52A1\u62A5\u8868\u7CFB\u7EDF
project.config.version=2.0.0

# redis \u914D\u7F6E # \u5730\u5740
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${CACHE_PWD}
spring.data.redis.database=1